### ISSUE TITLE
Add to django packages

### ISSUE THREAD

**Issue by lovelydinosaur** [mrhwick/django-rest-framework-version-transforms#3]
Looks interesting!

Make sure to add it to the 'REST framework' grid on Django packages when it's ready, to make it more visible to other users! https://www.djangopackages.com/grids/g/django-rest-framework/

**Comment by mrhwick** [comment]
Got it added in there, and everything looks good. The license was incorrect on the published pypi packages, but I fixed that and it'll update on the next release.

**Comment by lovelydinosaur** [comment]
Great!
